include:
  - project: r/operations/ci-cd-fragments
    ref: v4.0
    file: kaniko.yml
  - project: r/operations/ci-cd-fragments
    ref: v4.0
    file: dotnet.yml
  - project: r/operations/ci-cd-fragments
    ref: v4.0
    file: octopus.yml

stages:
  - build
  - test
  - deploy

variables:
  VERSION: 1.0.$CI_PIPELINE_IID
  DOTNET_VERSION: '10.0'

Build Image:
  extends: .kaniko-build
  variables:
    DOCKERFILE: 'Host/Dockerfile'

Build Executable:
  extends: .dotnet-publish
  variables:
    PROJECT_PATH: Host
    RUNTIME: win-x64

Integration tests:
  extends: .dotnet-test
  needs: [Build Executable]
  variables:
    PROJECT_PATH: Tests.IntegrationTests

Unit tests:
  extends: .dotnet-test
  needs: [Build Executable]
  variables:
    PROJECT_PATH: Tests.UnitTests

Publish to octopus:
  extends: .dotnet-octo-pack
  dependencies: [Build Executable]
  needs: [Build Executable, Integration tests, Unit tests]
  variables:
    OCTOPUS_ADDRESS: $OCTOPUS_NUGET_ADDRESS
    OCTOPUS_API_KEY: $OCTOPUS_API_KEY
